---
- name: Disable root SSH login
  hosts: all
  become: yes
  tasks:
    - name: Backup sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.backup
        remote_src: yes

    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        validate: '/usr/sbin/sshd -t -f %s'

    - name: Restart sshd service
      service:
        name: sshd
        state: restarted

    - name: Verify root SSH is disabled
      shell: sshd -T | grep permitrootlogin
      register: ssh_status
      changed_when: false

    - name: Show current SSH root login status
      debug:
        msg: "Root SSH login status: {{ ssh_status.stdout }}"
