- name: Setup SSH Key-Based Authentication for Service User
  hosts: all
  become: true
  vars:
    service_user: SVCSNowDisc
    ssh_key_file: "/tmp/{{ service_user }}_id_rsa"

  tasks:
    - name: Ensure the service user exists
      ansible.builtin.user:
        name: "{{ service_user }}"
        state: present

    - name: Generate SSH key pair locally (only on localhost)
      ansible.builtin.command:
        cmd: "ssh-keygen -t rsa -b 4096 -f {{ ssh_key_file }} -N ''"
        creates: "{{ ssh_key_file }}.pub"
      delegate_to: localhost
      run_once: true

    - name: Read public key from generated key pair
      ansible.builtin.slurp:
        src: "{{ ssh_key_file }}.pub"
      delegate_to: localhost
      register: public_key
      run_once: true

    - name: Ensure .ssh directory exists for service user on all hosts
      ansible.builtin.file:
        path: "/home/{{ service_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ service_user }}"
        group: "{{ service_user }}"

    - name: Distribute public key to authorized_keys on all hosts
      ansible.builtin.authorized_key:
        user: "{{ service_user }}"
        state: present
        key: "{{ public_key['content'] | b64decode }}"
        manage_dir: no

    - name: Copy private key to control machine (optional)
      ansible.builtin.copy:
        src: "{{ ssh_key_file }}"
        dest: "/home/{{ ansible_user }}/.ssh/{{ service_user }}_id_rsa"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      delegate_to: localhost
      run_once: true

    - name: Set proper permissions on .ssh directory for service user
      ansible.builtin.file:
        path: "/home/{{ service_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ service_user }}"
        group: "{{ service_user }}"
