---
# ssh-key-setup.yml
- name: Setup SSH Keys for ITOM Service Account
  hosts: all
  become: true
  vars:
    service_account: SVCSNowDisc
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_dir: "/var/lib/awx/.ssh"
  
  tasks:
    # Create SSH directory in Tower's home
    - name: Ensure SSH directory exists in Tower
      file:
        path: "{{ ssh_key_dir }}"
        state: directory
        mode: '0700'
        owner: awx
        group: awx
      delegate_to: localhost
      run_once: true

    # Generate SSH key using ssh-keygen command
    - name: Generate SSH key pair on Tower
      command: >
        ssh-keygen -t {{ ssh_key_type }} 
        -b {{ ssh_key_bits }}
        -C "{{ service_account }}@domain.com"
        -f {{ ssh_key_dir }}/{{ service_account }}_id_{{ ssh_key_type }}
        -N ""
      args:
        creates: "{{ ssh_key_dir }}/{{ service_account }}_id_{{ ssh_key_type }}"
      delegate_to: localhost
      run_once: true

    # Set proper permissions on the generated keys
    - name: Set permissions on SSH keys
      file:
        path: "{{ item }}"
        mode: "{{ '0600' if item.endswith('rsa') else '0644' }}"
        owner: awx
        group: awx
      with_items:
        - "{{ ssh_key_dir }}/{{ service_account }}_id_{{ ssh_key_type }}"
        - "{{ ssh_key_dir }}/{{ service_account }}_id_{{ ssh_key_type }}.pub"
      delegate_to: localhost
      run_once: true

    # Rest of the tasks remain the same
    - name: Create .ssh directory for service account
      file:
        path: "/home/{{ service_account }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ service_account }}"
        group: "{{ service_account }}"

    - name: Deploy public key to authorized_keys
      authorized_key:
        user: "{{ service_account }}"
        state: present
        key: "{{ lookup('file', '{{ ssh_key_dir }}/{{ service_account }}_id_{{ ssh_key_type }}.pub') }}"

    - name: Set correct permissions on service account .ssh directory
      file:
        path: "/home/{{ service_account }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ service_account }}"
        group: "{{ service_account }}"
        recurse: yes
