---
# inventory.yml
all:
  hosts:
    # Add your servers here
    server1.example.com:
    server2.example.com:
  vars:
    service_account: SVCSNowDisc
    ssh_key_type: rsa
    ssh_key_bits: 4096

---
# ssh-key-setup.yml
- name: Setup SSH Keys for ITOM Service Account
  hosts: all
  become: true
  vars_files:
    - inventory.yml
  
  tasks:
    # Generate key on the control node first (runs only once)
    - name: Generate SSH key pair locally
      openssh_keypair:
        path: "./{{ service_account }}_id_{{ ssh_key_type }}"
        type: "{{ ssh_key_type }}"
        bits: "{{ ssh_key_bits }}"
        comment: "{{ service_account }}@domain.com"
      delegate_to: localhost
      run_once: true

    # Ensure .ssh directory exists
    - name: Create .ssh directory if it doesn't exist
      file:
        path: "/home/{{ service_account }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ service_account }}"
        group: "{{ service_account }}"

    # Copy the public key to all servers
    - name: Deploy public key to authorized_keys
      authorized_key:
        user: "{{ service_account }}"
        state: present
        key: "{{ lookup('file', './{{ service_account }}_id_{{ ssh_key_type }}.pub') }}"

    # Ensure proper permissions
    - name: Set correct permissions on .ssh directory
      file:
        path: "/home/{{ service_account }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ service_account }}"
        group: "{{ service_account }}"
        recurse: yes
