---
# ssh-key-setup.yml
- name: Setup SSH Keys for ITOM Service Account
  hosts: all
  become: true
  vars:
    service_account: SVCSNowDisc
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_dir: "/var/lib/awx/.ssh"  # Ansible Tower's home directory
  
  tasks:
    # Create SSH directory in Ansible Tower's home with correct permissions
    - name: Ensure SSH directory exists in Tower
      file:
        path: "{{ ssh_key_dir }}"
        state: directory
        mode: '0700'
        owner: awx
        group: awx
      delegate_to: localhost
      run_once: true

    # Generate key on the Tower node
    - name: Generate SSH key pair on Tower
      openssh_keypair:
        path: "{{ ssh_key_dir }}/{{ service_account }}_id_{{ ssh_key_type }}"
        type: "{{ ssh_key_type }}"
        bits: "{{ ssh_key_bits }}"
        comment: "{{ service_account }}@domain.com"
        mode: '0600'
        owner: awx
        group: awx
      delegate_to: localhost
      run_once: true

    # Ensure target user's .ssh directory exists
    - name: Create .ssh directory for service account
      file:
        path: "/home/{{ service_account }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ service_account }}"
        group: "{{ service_account }}"

    # Copy the public key to all servers
    - name: Deploy public key to authorized_keys
      authorized_key:
        user: "{{ service_account }}"
        state: present
        key: "{{ lookup('file', '{{ ssh_key_dir }}/{{ service_account }}_id_{{ ssh_key_type }}.pub') }}"

    # Ensure proper permissions on target
    - name: Set correct permissions on service account .ssh directory
      file:
        path: "/home/{{ service_account }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ service_account }}"
        group: "{{ service_account }}"
        recurse: yes
