---
- name: Setup SSH Key-Based Authentication for Service User
  hosts: all
  become: true
  vars:
    ansible_user: 
    service_user: SVCSNowDisc
    ssh_key_dir: "svcnow"  # Path where keys are pre-generated
    ssh_key_file: "{{ ssh_key_dir }}/{{ service_user }}_id_rsa"
    
  tasks:
    - name: Ensure SSH key directory exists and has proper permissions
      ansible.builtin.file:
        path: "{{ ssh_key_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      delegate_to: localhost
      run_once: true

    - name: Ensure the service user exists
      ansible.builtin.user:
        name: "{{ service_user }}"
        state: present

    - name: Set proper permissions on SSH key files
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "{{ '0600' if item == ssh_key_file else '0644' }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      delegate_to: localhost
      run_once: true
      loop:
        - "{{ ssh_key_file }}"
        - "{{ ssh_key_file }}.pub"

    - name: Read public key from pre-generated key pair
      ansible.builtin.slurp:
        src: "{{ ssh_key_file }}.pub"
      delegate_to: localhost
      register: public_key
      run_once: true

    - name: Ensure .ssh directory exists for service user on all hosts
      ansible.builtin.file:
        path: "/home/{{ service_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ service_user }}"
        group: "{{ service_user }}"

    - name: Distribute public key to authorized_keys on all hosts
      ansible.builtin.authorized_key:
        user: "{{ service_user }}"
        state: present
        key: "{{ public_key['content'] | b64decode }}"
        manage_dir: no

    - name: Copy private key to control machine
      ansible.builtin.copy:
        src: "{{ ssh_key_file }}"
        dest: "/home/{{ ansible_user }}/.ssh/{{ service_user }}_id_rsa"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      delegate_to: localhost
      run_once: true

    - name: Set proper permissions on .ssh directory for service user
      ansible.builtin.file:
        path: "/home/{{ service_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ service_user }}"
        group: "{{ service_user }}"
