vars:
    ansible_user: netsys
    service_user: SVCSNowDisc
    ssh_key_dir: "/home/netsys/svcnow"
    ssh_key_file: "{{ ssh_key_dir }}/{{ service_user }}_id_rsa"
    
  tasks:
    - name: Ensure SSH key directory exists and has proper permissions
      ansible.builtin.file:
        path: "{{ ssh_key_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      delegate_to: localhost
      run_once: true

    - name: Ensure the service user exists
      ansible.builtin.user:
        name: "{{ service_user }}"
        state: present

    - name: Set proper permissions on SSH key files
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "{{ '0600' if item == ssh_key_file else '0644' }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      delegate_to: localhost
      run_once: true
      loop:
        - "{{ ssh_key_file }}"
        - "{{ ssh_key_file }}.pub"

    - name: Read public key from pre-generated key pair
      ansible.builtin.slurp:
        src: "{{ ssh_key_file }}.pub"
      delegate_to: localhost
      register: public_key
      run_once: true

    - name: Ensure .ssh directory exists for service user on all hosts
      ansible.builtin.file:
        path: "/home/{{ service_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ service_user }}"
        group: "{{ service_user }}"

    - name: Create authorized_keys file for service user
      ansible.builtin.file:
        path: "/home/{{ service_user }}/.ssh/authorized_keys"
        state: touch
        mode: '0600'
        owner: "{{ service_user }}"
        group: "{{ service_user }}"

    - name: Add public key to authorized_keys file
      ansible.builtin.lineinfile:
        path: "/home/{{ service_user }}/.ssh/authorized_keys"
        line: "{{ public_key['content'] | b64decode }}"
        state: present
        create: yes
        owner: "{{ service_user }}"
        group: "{{ service_user }}"
        mode: '0600'

    - name: Copy private key to control machine
      ansible.builtin.copy:
        src: "{{ ssh_key_file }}"
        dest: "/home/{{ ansible_user }}/.ssh/{{ service_user }}_id_rsa"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      delegate_to: localhost
      run_once: true

    - name: Set proper permissions on .ssh directory for service user
      ansible.builtin.file:
        path: "/home/{{ service_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ service_user }}"
        group: "{{ service_user }}"
